// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi7A5mA35fX6PshGnVE4m9DUSVO5X4Y4Y',
    appId: '1:322532190054:android:48246dc0ca730be8be8aa7',
    messagingSenderId: '322532190054',
    projectId: 'mercurycomputers-tech',
    storageBucket: 'mercurycomputers-tech.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9odEIg1BU0uQQqYzf6VzaOcm-hLNXFvk',
    appId: '1:322532190054:ios:037534086894992abe8aa7',
    messagingSenderId: '322532190054',
    projectId: 'mercurycomputers-tech',
    storageBucket: 'mercurycomputers-tech.firebasestorage.app',
    iosBundleId: 'com.mercurytech.mercuryTech',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN7l818Y1NdSe9ZNq5P3DEjkjrKlwHeKs',
    appId: '1:322532190054:web:7a10c7dff62aa3ffbe8aa7',
    messagingSenderId: '322532190054',
    projectId: 'mercurycomputers-tech',
    storageBucket: 'mercurycomputers-tech.firebasestorage.app',
    authDomain: 'mercurycomputers-tech.firebaseapp.com',
    measurementId: 'G-THBBERELQC',
  );
}
